# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Donald (Tony) Witt
title: Senior Mechanical Engineer
email: tony@tonywitt.com
website: tonywitt.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  theArgo15
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: donald-anthony-witt
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tony and I'm a senior mechanical engineer. As an experiment, I am making a personal website. Please see my resume below, and reach out via email if you are interesting in hearing more.

  I've also learned some <mark>python</mark> and am constantly finding ways to apply that in mechanical engineering.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Senior design project
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Three solutions for the price of one
        description: | # this will include new lines to allow paragraphs
          Envirox needed a portable dilution solution

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cummins Power Generation
        link: Cummins.com
        # link_text: cummins.com
        sub_title: Senior Mechanical Engineer, Engineering to Order (ETO)
        caption: August 2020 - April 2022
        quote: >
          Engineering to order means creating special engineering solutions on accelerated timelines fir strategic customers on a global scope
        description: | # this will include new lines to allow paragraphs
            Primary manager of all projects coming out of the ETO group: tracking orders, release processes, customer feedback, and prioritizing projects based on risk, development timelines, supplier lead-times and potential future sales.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Illinois Urbana-Champaign
        caption: May 2017
        sub_title: Bachelor of Science in Mechanical Engineering
        quote: >
          I-L-L
        description: | # this will include new lines to allow paragraphs
          U of I was a place for me to learn more than just the nuts and bolts of mehanical engineering. I learned to self manage, colaborate with a team, prioritize workloads, and utilize every resource available to solve problems.

          I spent a lot of my free time with the campus cycling and climbing teams, staying active, and getting outside.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Camping
      - 3D printing
      - Woodworking

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
